# Generated by Django 5.2.17 on 2026-09-21 04:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name='Part ichida savollarni aralashtirish')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paket',
                'verbose_name_plural': 'Paketlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Familiya')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Telefon')),
                ('language', models.CharField(blank=True, choices=[('ru', 'Русский'), ('en', 'English')], max_length=2, verbose_name='Til')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram foydalanuvchi',
                'verbose_name_plural': 'Telegram foydalanuvchilar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('math', 'Mathematics'), ('english', 'English'), ('iq', 'IQ / Logical Reasoning')], max_length=16, verbose_name="Yo'nalish")),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Tartib')),
                ('title_ru', models.CharField(blank=True, max_length=120, verbose_name='Sarlavha (RU)')),
                ('title_en', models.CharField(blank=True, max_length=120, verbose_name='Sarlavha (EN)')),
                ('instruction_ru', models.CharField(blank=True, max_length=255, verbose_name="Ko'rsatma (RU)")),
                ('instruction_en', models.CharField(blank=True, max_length=255, verbose_name="Ko'rsatma (EN)")),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='quiz.package')),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Partlar',
                'ordering': ['package', 'order', 'id'],
                'unique_together': {('package', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Tartib')),
                ('text_ru', models.TextField(verbose_name='Savol matni (RU)')),
                ('text_en', models.TextField(verbose_name='Savol matni (EN)')),
                ('image', models.ImageField(blank=True, upload_to='questions/', verbose_name='Rasm (ixtiyoriy)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.part')),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['part', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Tartib')),
                ('text_ru', models.CharField(max_length=500, verbose_name='Variant (RU)')),
                ('text_en', models.CharField(max_length=500, verbose_name='Variant (EN)')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.question')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
                'ordering': ['question', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], max_length=2, verbose_name='Til')),
                ('status', models.CharField(choices=[('in_progress', 'Jarayonda'), ('finished', 'Yakunlangan')], default='in_progress', max_length=16)),
                ('question_ids', models.JSONField(default=list)),
                ('current_index', models.PositiveIntegerField(default=0)),
                ('math_correct', models.PositiveIntegerField(default=0)),
                ('math_total', models.PositiveIntegerField(default=0)),
                ('english_correct', models.PositiveIntegerField(default=0)),
                ('english_total', models.PositiveIntegerField(default=0)),
                ('iq_correct', models.PositiveIntegerField(default=0)),
                ('iq_total', models.PositiveIntegerField(default=0)),
                ('total_correct', models.PositiveIntegerField(default=0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlangan')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugagan')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='quiz.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='quiz.telegramuser')),
            ],
            options={
                'verbose_name': 'Test natijasi',
                'verbose_name_plural': 'Test natijalari',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('math', 'Mathematics'), ('english', 'English'), ('iq', 'IQ / Logical Reasoning')], max_length=16)),
                ('is_correct', models.BooleanField(default=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('selected_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.testsession')),
            ],
            options={
                'verbose_name': 'Javob',
                'verbose_name_plural': 'Javoblar',
                'ordering': ['answered_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='testsession',
            index=models.Index(fields=['status', '-started_at'], name='quiz_testse_status_f3b144_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('session', 'question')},
        ),
    ]
