# Generated by Django 5.2.17 on 2026-09-21 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quiz.part')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_results', to='quiz.testsession')),
            ],
            options={
                'verbose_name': "Bo'lim natijasi",
                'verbose_name_plural': "Bo'lim natijalari",
                'ordering': ['part__order', 'part_id'],
                'unique_together': {('session', 'part')},
            },
        ),
    ]
