# Generated by Django 5.2.17 on 2026-09-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_backfill_partresults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['package', 'order', 'id'], 'verbose_name': "Bo'lim", 'verbose_name_plural': "Bo'limlar"},
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='english_correct',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='english_total',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='iq_correct',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='iq_total',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='math_correct',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='math_total',
        ),
        migrations.AlterField(
            model_name='part',
            name='title_en',
            field=models.CharField(max_length=120, verbose_name='Sarlavha (EN)'),
        ),
        migrations.AlterField(
            model_name='part',
            name='title_ru',
            field=models.CharField(max_length=120, verbose_name='Sarlavha (RU)'),
        ),
        migrations.RemoveField(
            model_name='part',
            name='category',
        ),
    ]
